export const data = [
  {
    image: '/images/yoga.jpg',
    category: 'Fitness',
    title: 'Sunset Yoga & Meditation',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere cum provident quisquam dolorum omnis expedita.',
    vendor: 'Zen Studio',
    price: 25,
  },
  {
    image: '/images/cooking.jpg',
    category: 'Cooking',
    title: 'Italian Cooking Masterclass',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere cum provident quisquam dolorum omnis expedita.',
    vendor: 'Chef Marco',
    price: 85,
  },
  {
    image: '/images/hiking.jpg',
    category: 'Outdoor',
    title: 'Mountain Hiking Adventure',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere cum provident quisquam dolorum omnis expedita.',
    vendor: 'Adventure Co.',
    price: 35,
  },
  {
    image: '/images/painting.jpg',
    category: 'Art & Crafts',
    title: 'Pottery & Ceramics Workshop',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere cum provident quisquam dolorum omnis expedita.',
    vendor: 'Clay House',
    price: 45,
  },
  {
    image: '/images/photography.jpg',
    category: 'Creative',
    title: 'Creative Photography Masterclass',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere cum provident quisquam dolorum omnis expedita.',
    vendor: 'Zen Studio',
    price: 45,
  },
];
